version: '3.8'

services:
  app:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - database
      - rabbitmq
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: ${BROKER_USER}
      RABBITMQ_PASSWORD: ${BROKER_PASS}

  database:
    image: mysql:5.7
    restart: always
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER:  ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS:  ${BROKER_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq_data:/var/lib/rabbitmq
      - ./.docker/rabbitmq_logs:/var/log/rabbitmq


